# Generated by Django 5.0.6 on 2024-07-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
