# Generated by Django 5.0.6 on 2024-07-04 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_discount_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount_percentage",
        ),
    ]
