# Generated by Django 5.0.6 on 2024-07-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_remove_product_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(
                blank="True", default="", max_length=500, null="True"
            ),
        ),
    ]
