# Generated by Django 5.0.6 on 2024-07-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="date_canceled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
